baseURL: https://hackforprivacy.org/
relativeURLs: true
canonifyURLs: true
languageCode: en-us
title: Hack for Privacy
theme: hugo_theme_beg

params:
  logo: /images/cryptofist.png
  twitter: https://twitter.com/hackforprivacy
  facebook: https://www.facebook.com/hackforprivacy/
  meetup: https://www.meetup.com/hack-for-privacy/
  slackjoin: https://cryptohack.herokuapp.com
  slack: https://hackforprivacy.slack.com
  rss: https://hackforprivacy.org/index.xml

menu:
  main:
      - Name: "About Us"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "about"
        URL: "/about.html"
      - Name: "Contribute"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/contribute.html"
